[package]
name = "aletheia-lattice"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
aletheia-algebra = { path = "../aletheia-algebra" }
num-rational.workspace = true
num-bigint.workspace = true
num-traits.workspace = true
smallvec.workspace = true
thiserror.workspace = true
